org: dillescas
service: api-web-scraping-earthquakes

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::940376243370:role/LabRole

functions:
  scrape_earthquakes:
    handler: scrap_earthquakes.lambda_handler  # Asegúrate de que el archivo sea "scrap_earthquakes.py" y la función "lambda_handler"
    package:
      include:
        - scrap_earthquakes.py
    events:
      - http:
          path: /scrape/earthquakes
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaSismos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaSismos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
